### ISSUE TITLE
Argument of type 'string | URL' is not assignable to parameter of type 'string'

### ISSUE THREAD

**Issue by David-Else** [gabrielfroes/youtube-chapter-extractor#15]
Running Linux
```
deno --version
deno 1.4.0
v8 8.7.75
typescript 4.0.2
```

```
deno run --allow-read --allow-net app.ts
Download https://deno.land/x/dotenv/mod.ts
Download https://deno.land/x/cors/mod.ts
Warning Implicitly using latest version (v1.2.0) for https://deno.land/x/cors/mod.ts
Download https://deno.land/x/cors@v1.2.0/mod.ts
Warning Implicitly using latest version (v0.5.0) for https://deno.land/x/dotenv/mod.ts
Download https://deno.land/x/dotenv@v0.5.0/mod.ts
Download https://deno.land/x/cors@v1.2.0/types.ts
Download https://deno.land/x/cors@v1.2.0/oakCors.ts
Download https://deno.land/x/cors@v1.2.0/abcCors.ts
Download https://deno.land/x/cors@v1.2.0/opineCors.ts
Download https://deno.land/x/cors@v1.2.0/mithCors.ts
Download https://deno.land/x/cors@v1.2.0/attainCors.ts
Download https://deno.land/x/dotenv@v0.5.0/util.ts
Download https://deno.land/x/cors@v1.2.0/cors.ts
Check file:///home/david/sites/youtube-chapter-extractor/api/app.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.53.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.53.0/path/posix.ts:433:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

Found 4 errors.
```

**Comment by David-Else** [comment]
This issue is over 2 years old with no replies, and I have no idea if it is relevant any more so will close it.
